[book]
authors = ["lencx"]
language = "zh_CN"
multilingual = false
src = "src"
title = "lencx's book"

# https://github.com/lzanini/mdbook-katex
[preprocessor.katex]

# https://github.com/badboy/mdbook-mermaid
[preprocessor.mermaid]
command = "mdbook-mermaid"

# [build]
# build-dir = "dist"

[output.html]
theme = "lencx"
default-theme = "rust"
google-analytics = "UA-76982222-5"
git-repository-url = "https://github.com/lencx/book"
additional-js = ["./plugins/mermaid.min.js", "./plugins/mermaid.init.js"]

[output.html.playground]
editable = true
copy-js = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 3
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true

[output.html.fold]
enable = true
level = 2
